# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccr" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "56ee6e9e9be9fe92a3a67b6ec2e8fe4e3b18015f62fef8205d9b8309d3a8e908"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e25a684729f09a2593c2abdbc6d4fe0ed87b421cbe220528e1b03b0a02fcbaaf"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "588c8203681c41560ad114ebcacae9e9c190e872fb86d3ace22a458172a3b143"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f78411e3796312f0969d49c21f31d04a34a6b5beb71ea82927bfb1791dee4bf"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_linux_arm64.tar.gz"
    end
  end

  name "ccr"
  desc "用选定 provider 的环境变量启动 claude，可同时多开、各用不同后端"
  homepage "https://github.com/ttsimon/cc-run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccr"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccr"]
    end
  end

  # No zap stanza required

end
