# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccr" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "c6de24ac103b70ba497c3412639b216d34dbd25ca4ba27a83a76d3152e70bb52"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1920d725e07d8122dee15d2ad4888949b84a4067dc17150d66d9e072880f7abb"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c91f01d1779ea1dab4d00d7acff973e2975223e3ee13c2fd800a8bfa4b9a5bda"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "183a5fcc29b7206bd1327d39a3de494c32e2cfcf1fd790947cc657d8aceec9f5"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_linux_arm64.tar.gz"
    end
  end

  name "ccr"
  desc "用选定 provider 的环境变量启动 claude，可同时多开、各用不同后端"
  homepage "https://github.com/ttsimon/cc-run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccr"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccr"]
    end
    # 装完自动注册补全（探测 $SHELL，写 ~/.zshrc 或 ~/.bashrc；幂等，失败不阻断安装）。
    system_command "#{staged_path}/ccr", args: ["completion", "install"]
  end

  # No zap stanza required

end
