# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccr" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "b319e57d8d74a5b4ff0eaf8643cd675827b134e432585896a02878be8eacaba0"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "558904ca461708c31273dcf45c011abb14730f396f8a80355f8d985186eb2444"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c902384e801585c65b7113375ff92ab751bf5b02c0290afca883b0cdc8473407"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "147964adef57d74a6da53673ad315fddaba58396d1580f0f6889ada42ed80090"
      url "https://github.com/ttsimon/cc-run/releases/download/v#{version}/ccr_linux_arm64.tar.gz"
    end
  end

  name "ccr"
  desc "用选定 provider 的环境变量启动 claude，可同时多开、各用不同后端"
  homepage "https://github.com/ttsimon/cc-run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccr"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccr"]
    end
    # 装完自动注册补全（探测 $SHELL，写 ~/.zshrc 或 ~/.bashrc；幂等，失败不阻断安装）。
    system_command "#{staged_path}/ccr", args: ["completion", "install"]
  end

  # No zap stanza required

end
